<!DOCTYPE html>
<html>
<head lang="en">
    <base href="/">
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title><?php echo $this->pageTitle; ?></title>
    <link rel="stylesheet" type="text/css" href="/vendor/angularjs-datepicker/dist/angular-datepicker.min.css" />
    <link rel="stylesheet" type="text/css" href="/vendor/animate-css/animate.min.css" />
    <link rel="stylesheet" type="text/css" href="/vendor/bootstrap-css/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/vendor/bootstrap-css/css/bootstrap-theme.min.css" />
    <link rel="stylesheet" type="text/css" href="/css/assets/layout.min.css" />
</head>
<body>
    <timetracker-top-bar></timetracker-top-bar>
    <div class="container-fluid">
        <div ng-view></div>
    </div>
    <script type="text/javascript" src="/vendor/requirejs/require.js" data-main="/js/app/requireConfig.js"></script>
</body>
</html>