<!DOCTYPE html>
<html>
<head lang="en">
    <base href="/">
    <meta charset="UTF-8" />
    <title><?php echo $this->pageTitle; ?></title>
    <link rel="stylesheet" type="text/css" href="/vendor/animate-css/animate.min.css" />
    <link rel="stylesheet" type="text/css" href="/vendor/bootstrap-css/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/vendor/bootstrap-css/css/bootstrap-theme.min.css" />
    <link rel="stylesheet" type="text/css" href="/css/assets/layout.min.css" />
</head>
<body>
    <timetracker-top-bar></timetracker-top-bar>
    <div class="container-fluid">
        <div ng-view></div>
    </div>
    <script type="text/javascript" src="/vendor/requirejs/require.js" data-main="/js/app/requireConfig.js"></script>
</body>
</html>